export const titles = {
    B1: "Hey a new screen!",
    B2: "Hey a new screen!",
    C1: "C level now",
    C2: "Its C Level",
    D1: "Hey a new screen!",
    D2: "Hey a new screen!",
    E1: "Its E Level",
    E2: "Its E Level",
    F1: "Hey a new screen!",
    F2: "Hey a new screen!",
    F3: "Hey a new screen!",
    F4: "Hey a new screen!",
    G1: "G level now",
    G2: "G level now",
    G3: "G level now",
    G4: "G level now",
    G5: "G level now",
    H1: "Hey a new screen!",
    H2: "Hey a new screen!",
    H3: "Hey a new screen!",
    H4: "Hey a new screen!",
    H5: "Hey a new screen!",
    I1: "Its I Level",
    I2: "Its I Level",
    I3: "Its I Level",
    Z1: "Gameover!",
    Z2: "Gameover!",
    Z3: "Gameover!",
    Z4: "Gameover!",
    Z5: "Gameover!",
    Z6: "Gameover!",
    Z7: "Gameover!",
    Z8: "Gameover!",
    Z9: "Gameover!"
};